# Generated by Django 3.2.5 on 2021-07-18 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0004_feed_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
