# Generated by Django 3.2.5 on 2021-07-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0005_auto_20210718_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='first_child',
            field=models.BooleanField(default=False),
        ),
    ]
