# Generated by Django 3.2.5 on 2021-07-19 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0006_post_first_child'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='first_child',
            new_name='is_first_child',
        ),
    ]
